### ISSUE TITLE
PvP Issue

### ISSUE THREAD

**Issue by NyhmsQuest** [srnyx/personal-phantoms#3] opened 2023-04-19 19:04 UTC
### Expected behavior

With PersonalPhantoms installed and World Guard region with PvP disabled, PvP should be disabled and not working.

### Actual behavior

Personal Phantoms somehow override World Guard PvP flag and makes it possible to do PvP in a world guard region with PvP disabled.

### Steps to reproduce

Make a region with World Guard and disabled PvP and install Personal Phantoms.

### Version

1.3.0

### Checks

- [X] I asked in the Discord to see whether this issue is in fact a bug that needs to be fixed.

### Anything else

Such a strange issue for this plugin to touch anything related to world guard region and pvp.

**Comment by Yertled** [comment] 2023-04-19 19:07
Also no idea how a phantom plugin affects pvp but

**Comment by srnyx** [comment] 2023-04-19 19:25
What Minecraft version and server software (+ version)?

**Comment by NyhmsQuest** [comment] 2023-04-19 19:26
git-Purpur-1959 (MC: 1.19.4)*
Using 1.19.4 client

**Comment by srnyx** [comment] 2023-04-20 03:13
Sorry I forgot to reply lmao
I tested this on my own machine with the given versions and I can confirm it's reproducible. I tried messing around with the plugin's listener priorities and such so that it doesn't interfere with other plugins (such as WorldGuard), but for some reason it still breaks it. Even after I remove the entity damage listener, which makes me believe it's either something in my API (uh oh), another listener in Personal Phantoms, or just some weird incompatibility between the 2 that I'd have to investigate more.
If anyone else has got any ideas please let me know! *If someone could try testing this using Personal Phantoms v1.2.0 (with Purpur-1959 1.19.4) that'd be greatly appreciated 🙏*

**Comment by srnyx** [comment] 2023-05-25 23:15
I randomly found the cause while looking through my API, and it turns out it affects much more than just Personal Phantoms (it affects all my plugins 😭)...

I made a new issue on the API's GitHub, you can track it here: https://github.com/srnyx/annoying-api/issues/5
I'll be closing this issue now as it's no longer explicitly relevant to Personal Phantoms!

**Closed by srnyx** 2023-05-25 23:15 UTC
Labels: bug, help wanted
